class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '-----' },
    { id: 1, name: '国内小説' },
    { id: 2, name: '海外小説' },
    { id: 3, name: 'エンターテイメント小説' },
    { id: 4, name: 'ミステリー' },
    { id: 5, name: '恋愛' },
    { id: 6, name: '純文学' },
    { id: 7, name: '時代小説' },
    { id: 8, name: 'ライトノベル' },
    { id: 9, name: 'エッセイ'},
    { id: 10, name: '古典' },
    { id: 11, name: '科学' },
    { id: 12, name: 'SF' },
    { id: 13, name: '哲学' },
    { id: 14, name: '芸術' },
    { id: 15, name: '評論' },
    { id: 16, name: '社会' },
    { id: 17, name: 'ビジネス' },
    { id: 18, name: 'インターネット'},
    { id: 19, name: 'サブカル' },
    { id: 20, name: '映画' },
    { id: 21, name: 'アニメ' },
    { id: 22, name: 'ヨーロッパ' },
    { id: 23, name: 'アメリカ' },
    { id: 24, name: 'アジア' },
    { id: 25, name: '教育' },
    { id: 26, name: '法律' },
    { id: 27, name: '経済' },
    { id: 28, name: '環境' },
    { id: 29, name: '絵本' },
    { id: 30, name: '児童書' },
    { id: 31, name: '写真' },
    { id: 32, name: '数学' },
    { id: 33, name: '音楽' },
    { id: 34, name: '工学' },
    { id: 35, name: '歴史' },
    { id: 36, name: '医療' },
    { id: 37, name: '宗教' },
    { id: 38, name: '生物' },
    { id: 39, name: '人類' },
    { id: 40, name: '建築' },
    { id: 41, name: 'デザイン'},
    { id: 42, name: '心理学' },
    { id: 43, name: 'その他' }
  
  ]
  include ActiveHash::Associations
  has_many :intros
end
